services:
  all-hands-ai:
    image: 'docker.all-hands.dev/all-hands-ai/openhands:0.44'
    container_name: openhands-app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - './openhands-state:/.openhands-state'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - LOG_ALL_EVENTS=true
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.44-nikolaik
      - LLM_BASE_URL=http://xxx.xxx.xxx:11434 # Example url for Ollama server over Tailscale
    tty: true
    stdin_open: true
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openhands.entrypoints=web"
      - "traefik.http.routers.openhands.rule=Host(`openhands.yourdomain.com`)"
      - "traefik.http.routers.openhands.middlewares=redirect-to-https"
      - "traefik.http.routers.openhands-secure.entrypoints=websecure"
      - "traefik.http.routers.openhands-secure.rule=Host(`openhands.yourdomain.com`)"
      - "traefik.http.routers.openhands-secure.tls=true"
      - "traefik.http.routers.openhands-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.openhands-secure.middlewares=authentik,secure-headers"
      - "traefik.http.routers.openhands-secure.service=openhands-service"
      - "traefik.http.services.openhands-service.loadbalancer.server.port=3000"

networks:
  proxy:
    external: true
