services:
  enclosed:
    image: corentinth/enclosed
    #ports:
    #  - 8787:8787
    volumes:
      - /home/ubuntu/docker/enclosed:/app/.data
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      # HTTP Router – redirect to HTTPS
      - "traefik.http.routers.enclosed.entrypoints=web"
      - "traefik.http.routers.enclosed.rule=Host(`enclosed.yourdomain.com`)"
      - "traefik.http.routers.enclosed.middlewares=redirect-to-https"

      # HTTPS Router – secured by Authentik + secure headers
      - "traefik.http.routers.enclosed-secure.entrypoints=websecure"
      - "traefik.http.routers.enclosed-secure.rule=Host(`enclosed.yourdomain.com`)"
      - "traefik.http.routers.enclosed-secure.tls=true"
      - "traefik.http.routers.enclosed-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.enclosed-secure.middlewares=authentik,secure-headers"
      - "traefik.http.routers.enclosed-secure.service=enclosed-service"

      # Service Port
      - "traefik.http.services.enclosed-service.loadbalancer.server.port=8787"

networks:
  proxy:
    external: true
