services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myapp.entrypoints=web"
      - "traefik.http.routers.myapp.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.myapp.middlewares=redirect-to-https"
      - "traefik.http.routers.myapp-secure.entrypoints=websecure"
      - "traefik.http.routers.myapp-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.myapp-secure.tls=true"
      - "traefik.http.routers.myapp-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.myapp-secure.middlewares=secure-headers"
      - "traefik.http.routers.myapp-secure.service=myapp-service"

      # Internal service port
      - "traefik.http.services.myapp-service.loadbalancer.server.port=5678"
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./local_files:/files

networks:
  proxy:
    external: true
