services:
  gitea:
    image: gitea/gitea:1.21.4
    container_name: gitea
    ports: 
      - 2222:22
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=${GITEA_DB_USER}
      - GITEA__database__PASSWD=${GITEA_DB_PASSWORD}
    restart: always
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.entrypoints=web"
      - "traefik.http.routers.gitea.rule=Host(`gitea.yourdomain.com`)"
      - "traefik.http.routers.gitea.middlewares=redirect-to-https"
      - "traefik.http.routers.gitea-secure.entrypoints=websecure"
      - "traefik.http.routers.gitea-secure.rule=Host(`gitea.yourdomain.com`)"
      - "traefik.http.routers.gitea-secure.tls=true"
      - "traefik.http.routers.gitea-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.gitea-secure.middlewares=secure-headers"
      - "traefik.http.routers.gitea-secure.service=gitea-service"
      - "traefik.http.services.gitea-service.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
    security_opt:
      - no-new-privileges:true

  db:
    image: postgres:14
    container_name: gitea-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - proxy


  rclone-backup:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rclone-backup
    environment:
      - PGPASSWORD=${PGPASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - ./gitea:/data:ro
      - ./backups:/backups
      - ./rclone:/config/rclone
      - ./scripts:/scripts:ro
    networks:
      - proxy
    depends_on:
      - gitea
      - db

networks:
  proxy:
    external: true
