services:
  macos:
    image: dockurr/macos
    container_name: macos
    environment:
      VERSION: "15" # Or "14" for Sonoma, "12" for Monterey, etc.
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - "8006:8006"
      - 5900:5900/tcp
      - 5900:5900/udp
    volumes:
      - ./macos:/storage
    restart: always
    stop_grace_period: 2m