services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    # For GPU support. Uncomment if there is no GPU available.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11434:11434"  # Expose Ollama's HTTP API to your local network
    tty: true
    restart: unless-stopped